#%RAML 1.0
---
title: description
baseUri: http://nidi.guru/{path}
version: v1
baseUriParameters:
  path:
annotationTypes:
  simple:

/bla/{param}:
  uriParameters:
    param:
  get:
    queryParameters:
      ok:
    headers:
      ok:
    body:
      application/x-www-form-urlencoded:
    responses:
      200:
        headers:
          ok:
