#%RAML 1.0
---
title: example
baseUri: http://nidi.guru/raml/{version}
version: v1
schemas:
  String:
    schema: !include string.json

/empty:
/nonEmpty:
  get:
  /sub:
    get:
/ok:
  post:
    queryParameters:
      a:
      b:
        type: boolean
      c:
        type: integer
        minimum: 5
      d:
        type: file
      q:
        type: number
        example:
          strict: false
          value: 10
        default: 2
        minimum: 4
        maximum: 8
    body:
      application/json:
        schema: |
          {"type":"string"}
        example: |
          "42"
    responses:
      200:
/okref:
  post:
    body:
      application/json:
        schema: string
        example: |
          "42"
    responses:
      200:

/nok:
  post:
    body:
      application/json:
        schema: string
        example:
          strict: false
          value: 42
    responses:
      200:
        body:
          application/json:
            schema: string
            example: "42"
      201:
        body:
          application/json:
            example: 42
