#%RAML 1.0
---
title: jaxrs
baseUri: http://localhost:{port}/app
version: v1
mediaType: application/default

/path:
  post:
    queryParameters:
      qp:
    headers:
      h:
    body:
      text/plain:
    responses:
      200:
        headers:
          res:
        body:
          application/json:

