#%RAML 1.0
---
title: query
baseUri: http://nidi.guru/raml/{version}
version: v1
mediaType: application/default
schemas:
  String:
    schema: !include string.json
  User:
    properties:
      names:
        type: string[]
      age:

/data:
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              {"type":"string"}
/query:
  get:
    queryParameters:
      rep:
        required: false
        type: string[]
      req:
      int:
        required: false
        type: integer
    responses:
      200:
        body:
          application/json:
            schema: |
              {"type":"string"}
/queryString:
  get:
    queryString:
      type: User