#%RAML 1.0
---
title: type
baseUri: http://nidi.guru/raml/{version}
version: v1

/type:
  get:
    queryParameters:
      boolean:
        type: boolean
        required: false
      integer:
        type: integer
        required: false
      number:
        type: number
        required: false
      integerLimit:
        type: integer
        minimum: -5
        maximum: 666
        required: false
      numberLimit:
        type: number
        minimum: 5e-2
        maximum: 666.5
        required: false
      string:
        type: string
        minLength: 2
        maxLength: 5
        required: false
      date-only:
        type: date-only
        required: false
      time-only:
        type: time-only
        required: false
      datetime-only:
        type: datetime-only
        required: false
      datetime:
        type: datetime
        format: rfc2616
        required: false
      enum:
        enum: ['a','b']
        required: false
      pattern1:
        pattern: \d{2}/[a-y]
        required: false
    responses:
      200:
        body:
          '*/*':
/empty:
  post:
    responses:
      200:
        body:
          application/json:
            schema: !include string.json
      201:
        body:
      202:
