#%RAML 1.0
---
title: uri
baseUri: http://{+host}/{+root}/{version}/{undefined}
version: v1
protocols: ['HTTP','HTTPS']
baseUriParameters:
  host:
    enum: ['nidi.guru']
  root:
    enum: ['raml']

/concat/{name}{extension}:
  uriParameters:
    name:
    extension:
      enum: [.xml, .json]
  get:
    responses:
      200:

/type:
  get:
    protocols: ['HTTP']
    responses:
      200:
  /sub:
    get:
      responses:
        201:
  /{undefined}:
    uriParameters:
      undefined:
        type: integer
    get:
      responses:
        202:
    /sub:
      uriParameters:
        undefined:
          type: string
      get:
        responses:
          203:
/bu:
  get:
    responses:
      200:
  /sub:
    get:
      responses:
        200: