#%RAML 1.0
---
title: example
baseUri: http://nidi.guru/{path}
version: v1
baseUriParameters:
  path:
  invalid:
  version:

/bla/{param}:
  uriParameters:
    param:
    uriInvalid:
    version:
  get:
    queryParameters:
      ok:
      Nok:
    headers:
      ok:
      Hok:
    body:
      application/x-www-form-urlencoded:
    responses:
      200:
        headers:
          ok:
          Rok:
  /subA/{p}:
    uriParameters:
      param:
      p:
      subinvalid: