#%RAML 0.8
---
title: uri
baseUri: http://nidi.guru/raml/{version}/{undefined}
version: v1

/type:
  get:
    responses:
      200:
  /sub:
    get:
      responses:
        201:
  /{undefined}:
    uriParameters:
      undefined:
        type: integer
    get:
      responses:
        202:
    /sub:
      uriParameters:
        undefined:
          type: string
      get:
        responses:
          203:
